# Generated by Django 5.2.12 on 2026-03-08 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(help_text='Cuándo ingresa el cliente/organización')),
                ('fecha_hora_liberacion', models.DateTimeField(help_text='Cuándo termina la limpieza y se libera el salón')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('precio_historico_salon', models.DecimalField(decimal_places=2, help_text='Precio del salón o paquete al momento de reservar', max_digits=10)),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero ingresado (seña o total)', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(blank=True, help_text='Dejar en blanco si es a medida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.paquete')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalogo.salon')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoevento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('salon', 'fecha_hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Puntuación del 1 al 5')),
                ('comentario', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.CreateModel(
            name='ReservaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_historico_adicional', models.DecimalField(decimal_places=2, help_text='Precio congelado de este extra', max_digits=10)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.adicional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_contratados', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Adicional de Reserva',
                'verbose_name_plural': 'Adicionales de Reserva',
            },
        ),
    ]
