# Generated by Django 5.2.12 on 2026-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_historico_salon',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se autocompleta con el precio del salón/paquete al reservar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservaadicional',
            name='precio_historico_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se autocompleta con el precio actual del extra', max_digits=10, null=True),
        ),
    ]
