# Generated by Django 5.2.12 on 2026-03-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_actual', models.DecimalField(decimal_places=2, help_text='Precio actual del servicio', max_digits=10)),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Evento (Ej: 15 Años, Corporativo)')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Cantidad máxima de personas permitidas')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio actual del alquiler', max_digits=10)),
                ('adicionales_disponibles', models.ManyToManyField(blank=True, related_name='salones', to='catalogo.adicional')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_combo', models.CharField(help_text='Ej: Fiesta 15 Oro', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('max_invitados', models.PositiveIntegerField()),
                ('precio_paquete_actual', models.DecimalField(decimal_places=2, help_text='Precio total cerrado por el combo', max_digits=10)),
                ('adicionales_incluidos', models.ManyToManyField(blank=True, related_name='paquetes', to='catalogo.adicional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='catalogo.salon')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='catalogo.tipoevento')),
            ],
            options={
                'verbose_name': 'Paquete / Combo',
                'verbose_name_plural': 'Paquetes / Combos',
            },
        ),
    ]
