# Generated by Django 5.2.12 on 2026-03-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='salones/portadas/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Evento'),
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='salones/galeria/')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Vista de la pista de baile', max_length=100, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalogo.salon')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
            },
        ),
    ]
